apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-master-deployment
  namespace: kubernetes-cluster-devanshugoyal
  labels:
    app: dotnet-app-master
spec: 
  replicas: 4
  selector:
    matchLabels:
        app: dotnet-app-master
        template:
    metadata:
        labels:
          app: dotnet-app-master
    spec:
      containers:
        - name: dotnet-app-master
          image: devanshu123/devanshugoyal-master:latest
          ports:
            -  name: http
               containerPort: 80
               protocol: TCP
