apiVersion: v1
kind: Service
metadata: 
    name: dotnet-app-develop
    namespace: kubernetes-cluster-devanshugoyal
spec: 
   type: NodePort
   selector:
       app: dotnet-app-develop
   ports:
      - protocol: TCP
        nodePort: 30158
        port: 80
        targetPort: 80
